apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: taskflow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      tolerations:
        - key: "layer"
          operator: "Equal"
          value: "application"
          effect: "NoSchedule"
      nodeSelector:
        layer: "application"
      containers:
        - name: frontend
          image: ajeetkrup1234/taskflow-frontend:latest
          ports:
            - containerPort: 80
              name: http
          env:
            # Vite environment variables (build-time)
            - name: VITE_API_BASE_URL
              value: "http://a5bfaa3b2e48047f18ccfdad4d8589ed-761cc3edb90c97ea.elb.us-west-2.amazonaws.com/"
            # Runtime environment variables
            - name: NODE_ENV
              value: "production"
            - name: NGINX_ENTRYPOINT_QUIET_LOGS
              value: "1"
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
              readOnly: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          # Startup probe to handle slow container starts
          startupProbe:
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 6
      volumes:
        - name: nginx-config
          configMap:
            name: frontend-nginx-config
            defaultMode: 0644