apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: taskflow
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090  # Internal service name
      isDefault: true
      editable: true