apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: taskflow
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin123" # Change this in production!
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
            # This is the key: Set root URL without subpath since ingress handles it
            - name: GF_SERVER_ROOT_URL
              value: "%(protocol)s://%(domain)s:%(http_port)s/"
            # This is critical: DON'T serve from subpath since ingress rewrites
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "false"
            # Don't enforce domain
            - name: GF_SERVER_ENFORCE_DOMAIN
              value: "false"
            # Disable redirect enforcement
            - name: GF_SERVER_REDIRECT_OTHER_PORTS
              value: "false"
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-dashboards-config
              mountPath: /etc/grafana/provisioning/dashboards
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
        - name: grafana-dashboards-config
          configMap:
            name: grafana-dashboards-config