apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: taskflow
type: Opaque
data:
  # JWT Configuration (BASE64 encoded)
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtdGhpcy1pbi1wcm9kdWN0aW9u
  
  # Database Credentials (BASE64 encoded)
  DB_PASSWORD: bXlwYXNzd29yZA==
  DB_USER: bXl1c2Vy
  
  # Redis Password (BASE64 encoded)
  # REDIS_PASSWORD: cmVkaXNfcGFzc3dvcmQ=

  # Email creds
  EMAIL_USER: YWplZXRrcnVwNDAxQGdtYWlsLmNvbQo=
  EMAIL_PASSWORD: Z3JqZHdiY2V2Y2t4b3BuZgo=