apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: taskflow
spec:
  selector:
    app: notification-service
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP