apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: taskflow
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30001  
  selector:
    app: prometheus